string(TOLOWER ${PROJECT_NAME} PROJECT_ID)
list(APPEND PROJECT_CATEGORIES "Qt;Image")
list(APPEND PROJECT_KEYWORDS   "Image;Converter;Compression;Cropping;Effects;Enhancement;Erase;Gifgeneration;Inpainting")
set(PROJECT_AUTHOR_NAME        "weichangk")
set(PROJECT_AUTHOR_EMAIL       "nukgnahciew@gmail.com")
set(PROJECT_COPYRIGHT_YEAR     "2024-2025")
set(PROJECT_DESCRIPTION        "ImageKit")
set(PROJECT_ORGANIZATION_NAME  "weichangk")
set(PROJECT_ORGANIZATION_URL   "https://github.com/weichangk/ImageKit")
