@startuml

class accelerate-kernels-private
class accelerate-private
class animate-private
class animate
class annotate-private
class annotate
class artifact
class attribute
class blob-private
class blob
class cache-private
class cache-view
class cache
class channel
class cipher
class client
class coder-private
class coder
class color-private
class color
class colormap-private
class colormap
class colorspace-private
class colorspace
class compare
class composite-private
class composite
class compress
class configure-private
class configure
class constitute-private
class constitute
class decorate
class delegate-private
class delegate
class deprecate
class display-private
class display
class distort
class distribute-cache-private
class distribute-cache
class draw-private
class draw
class effect
class enhance
class exception-private
class exception
class feature
class fourier
class fx-private
class fx
class gem-private
class gem
class geometry-private
class geometry
class histogram
class identify
class image-private
class image-view
class image
class layer
class linked-list-private
class linked-list
class list
class locale-private
class locale_
class log-private
class log
class magic-private
class magic
class magick-baseconfig
class magick-config
class magick-private
class magick-type
class magick
class MagickCore
class matrix-private
class matrix
class memory-private
class memory_
class method-attribute
class methods
class mime-private
class mime
class module-private
class module
class monitor-private
class monitor
class montage
class morphology-private
class morphology
class mutex
class nt-base-private
class nt-base
class nt-feature
class opencl-private
class opencl
class option-private
class option
class paint
class pixel-accessor
class pixel-private
class pixel
class policy-private
class policy
class prepress
class profile-private
class profile
class property
class quantize
class quantum-private
class quantum
class random-private
class random_
class registry-private
class registry
class resample-private
class resample
class resize-private
class resize
class resource-private
class resource_
class segment
class semaphore-private
class semaphore
class shear
class signature-private
class signature
class splay-tree
class static
class statistic-private
class statistic
class stream-private
class stream
class string-private
class string_
class studio
class thread-private
class thread_
class threshold
class timer-private
class timer
class token-private
class token
class transform-private
class transform
class type-private
class type
class utility-private
class utility
class version-private
class version
class vision
class visual-effects
class vms
class widget-private
class widget
class xml-tree-private
class xml-tree
class xwindow-private
class xwindow

@enduml
