#include "home/repository.h"

HomeRepository::HomeRepository() {
}

HomeRepository::~HomeRepository() {
}

QList<SFuncItemData> HomeRepository::datas() {
    return {
        SFuncItemData{
            EFunc::FuncConversion,
            EFuncItemBtnType::AddFile,
            "Image Converter",
            "Convert images to other formats.",
            "Start Now",
            "Add File(s)",
            false,
            false,
            QPixmap(":/QtmImg/img/common/v16toolcovers/ImageConverter.png"),
            QPixmap(),
            QPixmap(),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_arrowright_white.svg"),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_add_white.svg"),
        },
        SFuncItemData{
            EFunc::FuncCompression,
            EFuncItemBtnType::AddFile,
            "Image Compressor",
            "Batch compress image files without quality loss.",
            "Start Now",
            "Add File(s)",
            false,
            false,
            QPixmap(":/QtmImg/img/common/v16toolcovers/Compress.png"),
            QPixmap(),
            QPixmap(),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_arrowright_white.svg"),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_add_white.svg"),
        },
        SFuncItemData{
            EFunc::FuncUpsc,
            EFuncItemBtnType::AddFile,
            "Image Enhancer",
            "Batch enhance images with AI for improved clarity and quality.",
            "Start Now",
            "Add File(s)",
            false,
            false,
            QPixmap(":/QtmImg/img/common/v16toolcovers/AIImageEnhance.png"),
            QPixmap(),
            QPixmap(),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_arrowright_white.svg"),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_add_white.svg"),
        },
        SFuncItemData{
            EFunc::FuncErase,
            EFuncItemBtnType::AddFile,
            "Watermark Remover",
            "Batch remove watermarks from images.",
            "Start Now",
            "Add File(s)",
            false,
            false,
            QPixmap(":/QtmImg/img/common/v16toolcovers/AIRemoveWatermark.png"),
            QPixmap(),
            QPixmap(),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_arrowright_white.svg"),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_add_white.svg"),
        },
        SFuncItemData{
            EFunc::FuncBgRm,
            EFuncItemBtnType::AddFile,
            "Backgroung Remover",
            "Automatically remove backgrounds from images.",
            "Start Now",
            "Add File(s)",
            false,
            false,
            QPixmap(":/QtmImg/img/common/v16toolcovers/BGRemover.png"),
            QPixmap(),
            QPixmap(),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_arrowright_white.svg"),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_add_white.svg"),
        },
        SFuncItemData{
            EFunc::FuncCrop,
            EFuncItemBtnType::AddFile,
            "Image Crop",
            "Automatically crop image.",
            "Start Now",
            "Add File(s)",
            false,
            false,
            QPixmap(":/QtmImg/img/common/v16toolcovers/SmartTrim.png"),
            QPixmap(),
            QPixmap(),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_arrowright_white.svg"),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_add_white.svg"),
        },
        SFuncItemData{
            EFunc::FuncGifMk,
            EFuncItemBtnType::StartNow,
            "GIF Maker",
            "Create a GIF from multiple images.",
            "Start Now",
            "Add File(s)",
            false,
            false,
            QPixmap(":/QtmImg/img/common/v16toolcovers/Gifmaker.png"),
            QPixmap(),
            QPixmap(),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_arrowright_white.svg"),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_add_white.svg"),
        },
        SFuncItemData{
            EFunc::FuncThumbMk,
            EFuncItemBtnType::StartNow,
            "Thumbnail Maker",
            "Generate presonalized tumbnails by entering prompts",
            "Start Now",
            "Add File(s)",
            false,
            false,
            QPixmap(":/QtmImg/img/common/v16toolcovers/AIThumbnailMaker.png"),
            QPixmap(),
            QPixmap(),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_arrowright_white.svg"),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_add_white.svg"),
        },
        SFuncItemData{
            EFunc::FuncDownloader,
            EFuncItemBtnType::StartNow,
            "Image Downloader",
            "Batch download images from Instagram.",
            "Start Now",
            "Add File(s)",
            false,
            false,
            QPixmap(":/QtmImg/img/common/v16toolcovers/downloader.png"),
            QPixmap(),
            QPixmap(),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_arrowright_white.svg"),
            QPixmap(":/QtmImg/img/dark/v16/icon24/icon24_add_white.svg"),
        },
    };
}
