#include "home/repository.h"

HomeRepository::HomeRepository() {
}

HomeRepository::~HomeRepository() {
}

QList<SFuncItemData> HomeRepository::datas() {
    return {
        SFuncItemData{
            EFunc::FuncConversion,
            EFuncItemBtnType::AddFile,
            "功能1",
            "这是功能1的描述",
            false,
            false,
            QPixmap(":/images/thumbnail1.png"),
            QPixmap(),
            QPixmap(),
            QPixmap(),
            QPixmap(":/images/addfile_icon1.png")
        },
        SFuncItemData{
            EFunc::FuncCompression,
            EFuncItemBtnType::AddFile,
            "功能1",
            "这是功能1的描述",
            false,
            false,
            QPixmap(":/images/thumbnail1.png"),
            QPixmap(),
            QPixmap(),
            QPixmap(),
            QPixmap(":/images/addfile_icon1.png")
        },
        SFuncItemData{
            EFunc::FuncCropping,
            EFuncItemBtnType::AddFile,
            "功能1",
            "这是功能1的描述",
            false,
            false,
            QPixmap(":/images/thumbnail1.png"),
            QPixmap(),
            QPixmap(),
            QPixmap(),
            QPixmap(":/images/addfile_icon1.png")
        },
        SFuncItemData{
            EFunc::FuncErase,
            EFuncItemBtnType::AddFile,
            "功能1",
            "这是功能1的描述",
            false,
            false,
            QPixmap(":/images/thumbnail1.png"),
            QPixmap(),
            QPixmap(),
            QPixmap(),
            QPixmap(":/images/addfile_icon1.png")
        },
        SFuncItemData{
            EFunc::FuncEnhancement,
            EFuncItemBtnType::AddFile,
            "功能1",
            "这是功能1的描述",
            false,
            false,
            QPixmap(":/images/thumbnail1.png"),
            QPixmap(),
            QPixmap(),
            QPixmap(),
            QPixmap(":/images/addfile_icon1.png")
        },
        SFuncItemData{
            EFunc::FuncInpainting,
            EFuncItemBtnType::AddFile,
            "功能1",
            "这是功能1的描述",
            false,
            false,
            QPixmap(":/images/thumbnail1.png"),
            QPixmap(),
            QPixmap(),
            QPixmap(),
            QPixmap(":/images/addfile_icon1.png")
        },
        SFuncItemData{
            EFunc::FuncEffects,
            EFuncItemBtnType::AddFile,
            "功能1",
            "这是功能1的描述",
            false,
            false,
            QPixmap(":/images/thumbnail1.png"),
            QPixmap(),
            QPixmap(),
            QPixmap(),
            QPixmap(":/images/addfile_icon1.png")
        },
        SFuncItemData{
            EFunc::FuncGifGeneration,
            EFuncItemBtnType::AddFile,
            "功能1",
            "这是功能1的描述",
            false,
            false,
            QPixmap(":/images/thumbnail1.png"),
            QPixmap(),
            QPixmap(),
            QPixmap(),
            QPixmap(":/images/addfile_icon1.png")
        }
    };
}
